# Generated by Django 4.2 on 2023-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_user_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
