# Generated by Django 4.1.7 on 2023-04-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('utelas_height', models.CharField(max_length=5)),
                ('child_situation', models.CharField(max_length=250)),
                ('child_heart_rate', models.CharField(max_length=250)),
                ('appointment', models.DateField()),
                ('description', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_appointments', to='appointment.semesters')),
            ],
        ),
    ]
