# Generated by Django 4.1.7 on 2023-04-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterappointment',
            name='women',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_semesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
