# Generated by Django 4.1.7 on 2023-04-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant_time', models.IntegerField(max_length=2)),
                ('beget_time', models.IntegerField(max_length=2)),
                ('beget_date', models.DateField()),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('cell', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('Health_center', models.CharField(max_length=100)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
