# Generated by Django 4.1.7 on 2023-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Doctor'), ('W', 'Woman'), ('R', 'Receptionist'), ('HR', 'HR'), ('C', 'Consultator')], default='W', max_length=3),
        ),
    ]
