# Generated by Django 4.2 on 2023-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Doctor'), ('W', 'Woman'), ('R', 'Receptionist'), ('HR', 'HR'), ('O', 'Ordinary')], default='O', max_length=3),
        ),
    ]
