# Generated by Django 4.1.7 on 2023-04-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
    ]
